### PR TITLE
Open graph metadata

### PR DESCRIPTION
**Pull request by dipiash**
Микроразметка для более правильного отображения в социальных сетях.
Подробнее по [ссылке](http://ogp.me/).

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://dipiash-og-metadata.morsbox-rusrails-76a5f66ac8218e6fa9cf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://dipiash-og-metadata.morsbox-rusrails-76a5f66ac8218e6fa9cf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by dipiash** [comment]
Test in Vk:com : [image](https://cloud.githubusercontent.com/assets/14073668/9690734/a16c9818-5357-11e5-80cc-c2cbaebb4af0.png), for url: [link](http://dipiash-og-metadata.morsbox-rusrails-76a5f66ac8218e6fa9cf.ttrcloud.com/active-record-basics).

**Comment by dipiash** [comment]
Test in G+ :[image](https://cloud.githubusercontent.com/assets/14073668/9691821/6417fdd4-535e-11e5-8c88-66084f8eb0f8.png), for url: [link](http://dipiash-og-metadata.morsbox-rusrails-76a5f66ac8218e6fa9cf.ttrcloud.com/rails-database-migrations)

**Comment by Mik-die** [comment]
nice, let's try!

**Pull request merged**
